#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


VERBOTEN="master stable/mitaka stable/liberty stable/kilo"

CURRENT_BRANCH=`git branch --list --no-color | grep '^*' | sed 's/* //'`

function fail() {
    local branch=$1
    cat<<EOF
STOP THE PRESS!

You are trying to commit on the *$branch* branch
Surely you don't mean that?

If you really do, force the commit by adding --no-verify to the command.

EOF
    exit 1
}

# if we find a .gitreview, then check for unsafe branches
if [[ -e .gitreview ]]; then
    for branch in $VERBOTEN; do
        if [[ "$branch" == "$CURRENT_BRANCH" ]]; then
            fail $branch
        fi
    done
fi
